### ISSUE TITLE
Support for YubiKey API v2.0 + Support for TLSv1.2

### ISSUE THREAD

**Issue by ClosedCondition** [dscoduc/YubicoAuthProvider#1]
I'm NOT a developer! That's my IMHO:

1. The current version of the YubicoAuthProvider is using YubiKey API v1.1 and hence do not generate a nonce. 
2. Currently, api.yubico.com supports TLS1.2 and higher and not supporting 1.0 and 1.1 anymore. The explicit usage of TLS1.2 should be added to the code or request will generate an error `An existing connection was forcibly closed by the remote host`

To use TLS1.2, probaly, this line should be added:
`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12 | SecurityProtocolType.Tls13;`

**Comment by dscoduc** [comment]
I have updated the code to use the new Yubico 2.0 API libraries.
